sudo: required
language: python
install: true

services:
  - docker

env:
  global:
    - VERSION=1.${TRAVIS_BUILD_NUMBER}

before_script:
  - export REPO='appsecpipeline/base'
  - docker build -f dockers/base/dockerfile-base . -t appsecpipeline/base
  - sh build/docker-hub.sh $TRAVIS_BRANCH $REPO $VERSION

script:
  - |
    echo "Running test=$TEST"

matrix:
  - docker build -f dockers/base/dockerfile-base-tools . -t appsecpipeline/base-tools
  - docker build -f dockers/base/dockerfile-sast . -t appsecpipeline/sast
