tool:
  version: AppSecPipeline 0.5.0
  name: DefectDojo
  tags:
    - "Vulnerability Management"
    - "Report Consumer"
  type: "collector"
  description: "DefectDojo is a security program and vulnerability management tool. DefectDojo allows you to manage your application security program, maintain product and application information, schedule scans, triage vulnerabilities and push findings into defect trackers. Consolidate your findings into one source of truth with DefectDojo."
  docker: "appsecpipeline/base"
  url: https://github.com/OWASP/django-DefectDojo
  documentation: http://defectdojo.readthedocs.io/en/latest/
  parameters:
   - "api_key"
   - "host"
   - "product"
   - "dir"
   - "proxy"
  commands:
    parameters: "dir : Directory of security tool output."
    pre:
    exec: "python /usr/bin/tools/defectdojo/dojo_ci_cd.py"
    shell: False
    post:
    report:
    reportname:
    post:
    junit:
  profiles:
    all: "--api_key=$api_key --host=$host --product=$product  --dir reports"
    all_proxy: "--proxy=$proxy --api_key=$api_key --host=$host --product=$product  --dir reports"
