FROM ruby:2.4

RUN apt-get update \
    && apt-get upgrade -y \
    && apt-get install -y \
    build-essential \
    ca-certificates \
    git \
    python-pip \
    python2.7 \
    python2.7-dev

#Python dependency installs
RUN pip install pyyaml
RUN pip install requests
RUN pip install junit_xml_output
RUN pip install defectdojo_api

RUN mkdir /usr/bin/appsecpipeline/
ENV PATH="/usr/bin/appsecpipeline/tools:${PATH}"
COPY tools /usr/bin/appsecpipeline/tools

RUN chmod +x /usr/bin/appsecpipeline/tools/launch.py
RUN chmod +x /usr/bin/appsecpipeline/tools/junit.py

RUN useradd -o -u 1000 jenkins

ENV BRAKEMAN_VERSION=4.0

#WPScan install
RUN cd /tmp && git clone https://github.com/wpscanteam/wpscan-v3
RUN cd /tmp/wpscan-v3 && bundle install && rake install && cd ../

#Update WPScanner DB
#RUN wpscan --update

RUN gem install brakeman --version ${BRAKEMAN_VERSION} --no-format-exec

ENTRYPOINT ["launch.py"]

HEALTHCHECK --interval=1m --retries=2 --timeout=5s CMD python /usr/bin/appsecpipeline/tools/health.py
