FROM kalilinux/kali-linux-docker

ENV DEBIAN_FRONTEND noninteractive

RUN apt-get update \
    && apt-get upgrade -y \
    && apt-get install -y \
    build-essential \
    ca-certificates \
    git \
    python-pip \
    python2.7 \
    python2.7-dev \
    csvtool \
    openjdk-9-jre-headless \
    nikto \
    cloc \
    unzip \
    nmap

#Python dependency installs
RUN pip install -U pyyaml
RUN pip install -U requests
RUN pip install -U junit_xml_output
RUN pip install defectdojo_api

RUN mkdir /usr/bin/appsecpipeline/
ENV PATH="/usr/bin/appsecpipeline/tools:${PATH}"
COPY tools /usr/bin/appsecpipeline/tools

RUN chmod +x /usr/bin/appsecpipeline/tools/launch.py
RUN chmod +x /usr/bin/appsecpipeline/tools/junit.py

RUN useradd -o -u 1000 jenkins

#Python dependency installs
RUN pip install -U bandit

#Install Arachni, packaged apt-get install arachni doesn't work for some reason, hangs on BrowserCluster
ARG VERSION=1.5.1
ARG WEB_VERSION=0.5.12

RUN mkdir /usr/share/arachni && \
          wget -qO- https://github.com/Arachni/arachni/releases/download/v${VERSION}/arachni-${VERSION}-${WEB_VERSION}-linux-x86_64.tar.gz | tar xvz -C /usr/share/arachni --strip-components=1

RUN echo '#!/bin/bash\n\ncd /usr/share/arachni/bin/ && ./arachni "$@"' > /usr/bin/arachni
RUN echo '#!/bin/bash\n\ncd /usr/share/arachni/bin/ && ./arachni_reporter "$@"' > /usr/bin/arachni_reporter

RUN chmod +x /usr/bin/arachni
RUN chmod +x /usr/bin/arachni_reporter

#Install SSLLabs Scanner
ARG SSLLAB=1.4.0

RUN wget -qO- https://github.com/ssllabs/ssllabs-scan/releases/download/v${SSLLAB}/ssllabs-scan_${SSLLAB}-linux64.tgz | tar xvz -C /usr/bin --strip-components=1

#Jenkins user need write permissions on component cache
RUN chown -R jenkins: /usr/share/arachni/system/
USER jenkins

ENTRYPOINT ["launch.py"]

HEALTHCHECK --interval=1m --retries=2 --timeout=5s CMD python /usr/bin/appsecpipeline/tools/health.py
