FROM kalilinux/kali-linux-docker

ENV DEBIAN_FRONTEND noninteractive

RUN apt-get update \
    && apt-get upgrade -y \
    && apt-get install -y \
    build-essential \
    ca-certificates \
    git \
    python-pip \
    python2.7 \
    python2.7-dev

RUN apt-get install -y \
    nikto \
    cloc

RUN pip install -U pyyaml

#Copy pipeline executor to bin
COPY controller/launch.py /usr/bin/
COPY tools /usr/bin/tools

RUN chmod +x /usr/bin/launch.py
