FROM owasp/zap2docker-stable

USER root

RUN apt-get update \
    && apt-get upgrade -y \
    && apt-get install -y \
    build-essential \
    ca-certificates \
    git \
    python-pip \
    python2.7 \
    python2.7-dev

#Python dependency installs
RUN pip install pyyaml
RUN pip install requests
RUN pip install junit_xml_output
RUN pip install defectdojo_api

#Copy pipeline executor to bin
RUN mkdir /usr/bin/appsecpipeline/
ENV PATH="/usr/bin/appsecpipeline/tools:${PATH}"
COPY tools /usr/bin/appsecpipeline/tools
COPY tools/zap/zap-baseline.py /zap/

RUN chmod +x /usr/bin/appsecpipeline/tools/launch.py
RUN chmod +x /usr/bin/appsecpipeline/tools/junit.py

#RUN useradd -o -u 1000 jenkins
RUN usermod -u 1000 zap
RUN groupmod -g 1000 zap

USER zap

ENTRYPOINT ["launch.py"]

HEALTHCHECK --interval=1m --retries=2 --timeout=5s CMD python /usr/bin/appsecpipeline/tools/health.py
