FROM appsecpipeline/base

RUN apt-get install -y \
    nikto \
    cloc \
    unzip

#Python dependency installs
RUN pip install -U bandit

#Install Arachni, packaged apt-get install arachni doesn't work for some reason, hangs on BrowserCluster
ARG VERSION=1.5.1
ARG WEB_VERSION=0.5.12

RUN mkdir /usr/share/arachni && \
          wget -qO- https://github.com/Arachni/arachni/releases/download/v${VERSION}/arachni-${VERSION}-${WEB_VERSION}-linux-x86_64.tar.gz | tar xvz -C /usr/share/arachni --strip-components=1

RUN echo '#!/bin/bash\n\ncd /usr/share/arachni/bin/ && ./arachni "$@"' > /usr/bin/arachni
RUN echo '#!/bin/bash\n\ncd /usr/share/arachni/bin/ && ./arachni_reporter "$@"' > /usr/bin/arachni_reporter

RUN chmod +x /usr/bin/arachni
RUN chmod +x /usr/bin/arachni_reporter
#Jenkins user need write permissions on component cache
RUN chown -R jenkins: /usr/share/arachni/system/
