FROM ruby:2.4

RUN apt-get update \
    && apt-get upgrade -y \
    && apt-get install -y \
    build-essential \
    ca-certificates \
    git \
    python-pip \
    python2.7 \
    python2.7-dev

#Python dependency installs
RUN pip install pyyaml
RUN pip install requests
RUN pip install junit_xml_output
RUN pip install defectdojo_api

RUN mkdir /usr/bin/appsecpipeline/
ENV PATH="/usr/bin/appsecpipeline/tools:${PATH}"
COPY tools /usr/bin/appsecpipeline/tools

RUN chmod +x /usr/bin/appsecpipeline/tools/launch.py
RUN chmod +x /usr/bin/appsecpipeline/tools/junit.py

RUN useradd -o -u 1000 jenkins

ENV BRAKEMAN_VERSION=4.0

RUN gem install brakeman --version ${BRAKEMAN_VERSION} --no-format-exec
