FROM kalilinux/kali-linux-docker

ENV DEBIAN_FRONTEND noninteractive

RUN apt-get update \
    && apt-get upgrade -y \
    && apt-get install -y \
    build-essential \
    ca-certificates \
    git \
    python-pip \
    python2.7 \
    python2.7-dev \
    csvtool \
    openjdk-9-jre-headless \
    nikto \
    cloc \
    unzip \
    nmap

#Python dependency installs
RUN pip install -U pyyaml
RUN pip install -U requests
RUN pip install -U junit_xml_output
RUN pip install defectdojo_api

RUN mkdir /usr/bin/appsecpipeline/
ENV PATH="/usr/bin/appsecpipeline/tools:${PATH}"
COPY tools /usr/bin/appsecpipeline/tools

RUN chmod +x /usr/bin/appsecpipeline/tools/launch.py
RUN chmod +x /usr/bin/appsecpipeline/tools/junit.py

RUN useradd -o -u 1000 jenkins

#Python dependency installs
RUN pip install -U bandit

#Python dependency installs
RUN pip install -U bandit

RUN apt-get install -y \
    unzip

#Install dependency checker
RUN wget -O /tmp/dependency-check.zip https://bintray.com/jeremy-long/owasp/download_file?file_path=dependency-check-3.0.2-release.zip && \
    unzip /tmp/dependency-check.zip -d /usr/bin/ && \
    rm /tmp/dependency-check.zip

#Update the NVD local database for dependency checker
RUN /usr/bin/dependency-check/bin/dependency-check.sh --updateonly

RUN chown -R jenkins: /usr/bin/dependency-check
#Dependency check needs write permission on the data directory
RUN chmod -R u=rwx /usr/bin/dependency-check/data

USER jenkins

ENTRYPOINT ["launch.py"]
