FROM appsecpipeline/base

#Python dependency installs
RUN pip install -U bandit

RUN apt-get install -y \
    unzip

#Install depedency checker
RUN wget -O /tmp/dependency-check.zip https://bintray.com/jeremy-long/owasp/download_file?file_path=dependency-check-3.0.2-release.zip && \
    unzip /tmp/dependency-check.zip -d /usr/bin/ && \
    rm /tmp/dependency-check.zip

#Update the NVD local database for dependency checker
RUN /usr/bin/dependency-check/bin/dependency-check.sh --updateonly

RUN chown -R jenkins: /usr/bin/dependency-check
#Dependency check needs write permission on the data directory
RUN chmod -R u=rwx /usr/bin/dependency-check/data
