checkmarx:
  version: AppSecPipeline 0.5.0
  tags:
    - "Static Scanner"
  type: "static"
  name: "checkmarx"
  icon-sm:
  icon-lg:
  description: "Checkmarx is a source code analysis product that allows organization to scan uncompiled code and identify vulnerabilities."
  url: https://www.checkmarx.com/technology/static-code-analysis-sca/
  documentation: https://checkmarx.atlassian.net/wiki/spaces/KC/overview
  docker: appsecpipeline/base
  parameters:
   - "URL"
   - "USERNAME"
   - "PASSWORD"
   - "ADMIN-USERNAME"
   - "ADMIN-PASSWORD"
   - "CLIENT"
   - "RUN-SCAN-POLL"
  commands:
    pre:
    exec: "python /usr/bin/appsecpipeline/tools/appspider/AppSpider.py --url $url --username $username --password $password --admin-username $admin-username --admin-password $admin-password --client $client"
    shell: False
    report: "--output-file='{reportname}'"
    reportname: "VulnerabilitiesSummary.xml"
    post:
    junit:
  languages:
    - "ruby"
    - "java"
    - "c#.net"
    - "php"
    - "python"
    - "groovy"
    - "android"
    - "ios"
    - "html5"
    - "c++"
    - "vb.net"
    - "vb"
    - "pl/sql"
    - "perl"
    - "apex"
    - "scala"
    - "swift"
  profiles:
    all: "--run-scan-poll $run-scan-poll"
    active: "--checks=active/*"
    passive: "--checks=passive/*"
    fast: "--audit-forms --checks=xss --scope-page-limit=1"
    file_upload: "--checks=form_upload"
    xss: "--checks=xss"
    remote: "--checks=file_inclusion"
    command_exec: "--checks=os_cmd_injection"
    sqli: "--checks=sql_injection"
