git:
  version: AppSecPipeline 0.5.0
  name: git
  tags:
    - "Utility"
  type: "utility"
  description: "Git is a free and open source distributed version control system designed to handle everything from small to very large projects with speed and efficiency."
  docker: "appsecpipeline/base"
  url: https://git-scm.com/
  documentation: https://git-scm.com/docs/git
  parameters:
   - "GIT_URL"
   - "GIT_DEST"
  commands:
    parameters: "dir : Directory of security tool output."
    pre:
    exec: "git"
    shell: False
    post:
    report:
    reportname:
    post:
    junit:
  profiles:
    clone: "clone $GIT_URL $GIT_DEST"
