spotbugs:
  version: AppSecPipeline 0.5.0
  name: spotbugs
  tags:
    - "Static Code Analyzer"
  type: "static"
  description: "SpotBugs is a program which uses static analysis to look for bugs in Java code."
  docker: "appsecpipeline/sast"
  url: https://spotbugs.github.io/
  documentation: http://spotbugs-in-kengo-toda.readthedocs.io/en/latest/index.html
  parameters:
   - "COMPILE_LOC"
  commands:
    parameters: "COMPILE_LOC : Location of jar file. LOC=/temp/jar"
    pre:
    exec: "spotbugs -textui"
    shell: False
    post:
    report: "-xml -output {reportname} $COMPILE_LOC"
    reportname: "{timestamp}.xml"
    post:
    junit:
  languages:
    - "java"
  profiles:
    #Runs the full bandit scan
    all: "-effort:max"
