snyk:
  version: AppSecPipeline 0.5.0
  tags:
    - "Static Code Analyzer"
  type: "static"
  description: "Snyk continuously monitors your application's dependencies and lets you quickly respond when new vulnerabilities are disclosed."
  docker: "appsecpipeline/node"
  url: https://snyk.io/
  documentation: https://snyk.io/docs/
  parameters:
   - "SNYK_API_TOKEN"
  commands:
    pre: "snyk auth $SNYK_API_TOKEN"
    exec: "snyk"
    shell: True
    post:
    report: "--json > {reportname}"
    reportname: "{timestamp}.json"
    post:
    junit:
  languages:
    - "ruby"
    - "nodejs"
    - "java"
    - "python"
  profiles:
    all: "test ."
